#### Dataset params ###########################################################
window: 24
window_lag: 1
horizon_lag: 1
stride: 1
test_len: 0.2
val_len: 0.1


#### Model params #############################################################
model_name: psan
k: 15
nnodes: 325
in_dim: 3
out_dim: 1
nheads: 4
layers: 3


#### Training params ##########################################################
batch_inference: 32
batch_size: 16
batches_epoch: 300
split_batch_in: 1
epochs: 300
patience: 20
precision: 16
prediction_loss_weight: 1.0
grad_clip_val: 5.0
l2_reg: 0.0
scale_target: true
loss_fn: l1_loss
lr: 0.001
lr_scheduler: cosine
seed: 42
workers: 0
whiten_prob:
- 0.2
- 0.5
- 0.8